server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848 # 修改本机的host 文件
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # admin-service ADMIN-SERVICE  /admin-service/** -> 微服务（ADMIN-SERVICE）
      routes:
        - id: admin-service_router
          uri: lb://admin-service   # 转发到那个目的地
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1 # 当前端访问/admin/login - >login 将admin自动的去掉
        - id: online-service_router
          uri: lb://online-service
          predicates:
            - Path=/online/**
          filters:
            - StripPrefix=1
        - id: test_router
          uri: http://www.aliyun.com
          predicates:
            - Path=/product
            # /test->http://www.baidu.com 网关自己内部会构建请求去访问我们要访问的地址 GET:http://www.baidu.com/test
#    sentinel:
#      transport:
#        dashboard: sentinel-server:8858  # sentinel-dashboard 放在ecs 里面
#      datasource:
#        #        ds1.file:
#        #          file: classpath:gw-flow.json  # 网关 + API分组的限流
#        #          ruleType: gw_flow
#        ds1.nacos: #com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource 使用Nacos持久化我的sentinel 数据时，需要添加nacos-datasource的依赖
#          serverAddr: nacos-server:8848
#          dataId: gw-flow
#          ruleType: gw_flow
#        #
#        #        ds2.file:
#        #          file: classpath:api-group.json
#        #          ruleType: gw_api_group
#        ds2.nacos:
#          serverAddr: nacos-server:8848
#          dataId: api-group
#          ruleType: gw_api_group